### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by ekingunoncu** [HenryAlbu/auto-Instagram-posting-bot#20]
Hello I am facing an issue running app

pip3 install -r requirements.txt   works just fine without error
but after that when I try to run app I ger the error below

` auto-Instagram-posting-bot % python app.py 
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import PySimpleGUI as sg
ImportError: No module named PySimpleGUI
ekingunoncu@Ekin-MacBook-Air auto-Instagram-posting-bot % python3 app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import PySimpleGUI as sg
  File "/Library/Python/3.7/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/Library/Python/3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 103, in <module>
    import tkinter as tk
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'`

This is my environment:
Python 3.7.3
pip 19.0.3 
macos catalina

**Comment by HenryAlbu** [comment]
Can you try running:
`pip3 install PySimpleGUI`

and see if that fixes it.
