### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by WhoR3born** [HenryAlbu/auto-Instagram-posting-bot#24]
`Traceback (most recent call last):
  File "C:\Users\ASrosTOS\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\ASrosTOS\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\app.py", line 13, in long_operation_thread
    insta.loop_posting()
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\insta.py", line 160, in loop_posting
    post()
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\insta.py", line 108, in post
    autoit.control_set_text("Open", "Edit1", image_path)
  File "C:\Users\ASrosTOS\AppData\Local\Programs\Python\Python39\lib\site-packages\autoit\autoit.py", line 84, in wrapper
    raise AutoItError(err_msg)
autoit.autoit.AutoItError: Window/Control could not be found
`

what should i do?
running on vps

**Comment by WhoR3born** [comment]
and now getting this error
`Traceback (most recent call last):
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\app.py", line 5, in <module>
    import insta
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\insta.py", line 8, in <module>
    import ninegag
  File "C:\Users\ASrosTOS\Desktop\auto-Instagram-posting-bot-master\ninegag.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

when try to run app.py
