### ISSUE TITLE
module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by PinkeshGjr** [HenryAlbu/auto-Instagram-posting-bot#34]
Traceback (most recent call last):
  File "/Users/xx/Desktop/insta/auto-Instagram-posting-bot-master/app.py", line 3, in <module>
    import insta
  File "/Users/xx/Desktop/insta/auto-Instagram-posting-bot-master/insta.py", line 5, in <module>
    import autoit
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/autoit/__init__.py", line 6, in <module>
    from .autoit import options, properties, commands
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/autoit/autoit.py", line 28, in <module>
    AUTO_IT = ctypes.windll.LoadLibrary(dll_path)
AttributeError: module 'ctypes' has no attribute 'windll'

Note: I am using python3 in my mac os 12.0.1

**Comment by ghostlab101** [comment]
ctypes is a Windows Module. you have to run on windows
