### ISSUE TITLE
Errors pls help 

### ISSUE THREAD

**Issue by 2000Polas** [HenryAlbu/auto-Instagram-posting-bot#39]
Starting... Opening instagram Exception in thread Thread-1: Traceback (most recent call last): File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner self.run() File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run self._target(*self._args, **self._kwargs) File "C:\Users\jitka\auto-Instagram-posting-bot\app.py", line 11, in long_operation_thread insta.launch_inst() File "C:\Users\jitka\auto-Instagram-posting-bot\insta.py", line 25, in launch_inst driver = webdriver.Chrome(executable_path=r"chromedriver.exe", options=opts) File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__ RemoteWebDriver.__init__( File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__ self.start_session(capabilities, browser_profile) File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute self.error_handler.check_response(response) File "C:\Users\jitka\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by aftanjj** [comment]
INSTAGRAM CODE ERROR PLEASE CHAK COMMAND CONTACT EMAIL adj459100@gmail.com 


 THANKS FEED BACK

**Comment by aftanjj** [comment]
Hi
![Uploading 209151347-8adcbff6-f6d0-487a-96e3-ae2ab7f232e6.png…]()
