### ISSUE TITLE
no module named autoit

### ISSUE THREAD

**Issue by trinityseven0** [HenryAlbu/auto-Instagram-posting-bot#41]
C:\Users\adana\OneDrive\Masaüstü\instatestr\auto-Instagram-posting-bot>python app.py
Traceback (most recent call last):
  File "C:\Users\adana\OneDrive\Masaüstü\instatestr\auto-Instagram-posting-bot\app.py", line 3, in <module>
    import insta
  File "C:\Users\adana\OneDrive\Masaüstü\instatestr\auto-Instagram-posting-bot\insta.py", line 5, in <module>
    import autoit
ModuleNotFoundError: No module named 'autoit'

**Comment by iamjpsharma** [comment]
auto-Instagram-posting-bot % python app.py


Traceback (most recent call last):
  File "/Users/iamjpsharma/Documents/AI/auto-Instagram-posting-bot/app.py", line 3, in <module>
    import insta
  File "/Users/iamjpsharma/Documents/AI/auto-Instagram-posting-bot/insta.py", line 5, in <module>
    import autoit
ModuleNotFoundError: No module named 'autoit'
